services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data # Mount target for PostgreSQL data

  app:
    build: .
    environment:
      DB_NAME: mydatabase
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "4000:4000"
    depends_on:
      - db

    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
    # Named volume definition

